#include <iostream>
#include <vector>
#include <fstream>

#define BASES_LEN 4

using namespace std;



int count_base(string s, const char base) {
    int count = 0;

    for (char const c: s) {
        if (c == base) {
            count++;
        }
    }

    return count;
}

vector<int> count_bases(const string s) {
    
    vector<int> base_counts;
    char bases[BASES_LEN] = {'A','C','G','T'};

    for (int i = 0; i < BASES_LEN; i++) {
        int ans = count_base(s, bases[i]);
        base_counts.push_back(ans);
    }

    return base_counts;
}

int main() {
    string test = "AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC";
    string actual = "GGGTAGTCACGCCATTCCACCAGTTTTGTAACATCGATATGACGCTGTCAAAGGCTCATAAATTCGCCAGCGAGTCTCGCCAGGCGCCTTCAGACGAGGGTCTCAGACCGGACCGCTCAGTTGAGTCCCCTCAGTACCGTAGATCTCCCAGACTCCTTCCTCCGAGTAGTAATACGTTTACACCCGCAAAACTGGGGGGAACGGGTATTGAACAGGAGATCTGGGGGCGTGACACGTTGCTGGTTGCCAGTCCATTTTAAGAGCCTCGTCATTCTGACAAGAGCACGAAATCGAATAACTTAACTCGTGGACGATTCATGGCACGGCGCCGGAAGCGGCTCGTGTTTTCTTGTGTTAACTTCTAATTAATCACCTATAATGTTAGAAGCACCCAGCGACGTATAGACAAGGGGACGACAGAATTCACGCCAACGATCAATCGGCGAGTACTTCTGGCACTATTCCTCCGGGTTTGCATTCTCATGCAAAGGTCAGTGTGAATTTAAAGGGGTACGATAGTCGGTTTGGGTGATGCAACTCGGTACAGCAATGGGAACCGCATTCACAAGTCCGCTTATTCTTGCGCACAGTGTATGGCTCCGAACGCCAAATCCGCCACCTCTTGGATCTACCTCTCCCTTTGACGGTGTATCCTTTCCAAAAGCAATCATTCCTTCTAACTGATACTATGTATACAGCCTTACCGGCATCAGCGCAGTTGTATACGTTGGCGATTTCATCATGTCATTTCAGACGGTGTGAAGATTCGTCATACCTTTTGCTGATCATGCTTAAGCCTGTAAGGTGTGTTGGGCGGTCGTTATGCAAGTGGCCCATTTTTCGCTCGGGGACAGCCGTCTGAAAAGCGTAGATATGAAACGGCCCAAAAGCTGATCCGTACGGAAGGGATCCGTAACGGAGTGTTGGTAACAGCAGGGGGGCCAGGATGCCTTCCTGCGGTACTAGATGA";
    vector<int> counts = count_bases(actual);
    for (int i = 0; i < counts.size(); i++) {
        printf("%d ", counts[i]);
    }
    printf("\n");

    return 0;
}